FROM fluent/fluentd:v1.3-debian-1

MAINTAINER Siete_Frouws <s.frouws@mcroberts.nl>

USER root

# Install elasticsearch plugin for fluentd to communicate with the elasticsearch database.
RUN buildDeps="sudo make gcc g++ libc-dev" \
 && apt-get update \
 && apt-get install -y --no-install-recommends $buildDeps \
 && sudo gem install fluent-plugin-elasticsearch \
 && sudo gem sources --clear-all \
 && SUDO_FORCE_REMOVE=yes \
    apt-get purge -y --auto-remove \
                  -o APT::AutoRemove::RecommendsImportant=false \
                  $buildDeps \
 && rm -rf /var/lib/apt/lists/* \
 && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem

COPY ./fluent.conf /fluentd/etc/

USER fluent

#COPY entrypoint.sh /bin/

#ENTRYPOINT ["tini",  "--", "/bin/entrypoint.sh"]
