FROM fluent/fluentd:v1.3-debian-1

MAINTAINER Siete_Frouws <s.frouws@mcroberts.nl>

USER root

# Install elasticsearch plugin for fluentd to communicate with the elasticsearch database.
RUN buildDeps="sudo make gcc g++ libc-dev" \
 && apt-get update \
 && apt-get install -y --no-install-recommends $buildDeps \
 && sudo gem install fluent-plugin-elasticsearch \
 && sudo gem sources --clear-all \
 && SUDO_FORCE_REMOVE=yes \
    apt-get purge -y --auto-remove \
                  -o APT::AutoRemove::RecommendsImportant=false \
                  $buildDeps \
 && rm -rf /var/lib/apt/lists/* \
 && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem

## the block below can be removed if no local file is stored anymore in the `fluent.conf` file
# Make folder recursively with `-p`
RUN mkdir -p /var/log/fluent
# `change owner` of the folder to `fluent`. The current user is `root`.
RUN chown fluent /var/log/fluent
# `change ...` of the folder for `o`, the owner, to `rwx`, read write execute. Where the owner is now `fluent`.
RUN chmod o-rwx /var/log/fluent

COPY ./fluent.conf /

USER fluent

#COPY entrypoint.sh /bin/
CMD [ "fluentd", "-c", "/fluent.conf" ]

#ENTRYPOINT ["tini",  "--", "/bin/entrypoint.sh"]
