version: '3.7'
services:
  merging_results_1:
    image: merging_results:1.5.2
    build: .
    environment:
      - PROCESS_NAME=merging_results
      - PROCESS_VERSION=1.5.2
      - BEHAVIOUR_OF_TEST_PROCESS=create1job
      - MULTIPLE_INPUTS_PROCESS=True
    env_file:
      - ./.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: es.${HOSTNAME}.merging_results.{{.ID}}
        fluentd-async-connect: "true"
        fluentd-sub-second-precision: "true"
 

  merging_results_2:
    image: merging_results:1.5.2
    build: .
    environment:
      - PROCESS_NAME=merging_results
      - PROCESS_VERSION=1.5.2
      - BEHAVIOUR_OF_TEST_PROCESS=create1job
      - MULTIPLE_INPUTS_PROCESS=True
    env_file:
      - ./.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: es.${HOSTNAME}.merging_results.{{.ID}}
        fluentd-async-connect: "true"
        fluentd-sub-second-precision: "true"


  classification_1:
    image: classification:9.1.0
    build: .
    environment:
      - PROCESS_NAME=classification
      - PROCESS_VERSION=9.1.0
      - BEHAVIOUR_OF_TEST_PROCESS=create1job
    env_file:
      - ./.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: es.${HOSTNAME}.classification.{{.ID}}
        fluentd-async-connect: "true"
        fluentd-sub-second-precision: "true"


  classification_2:
    image: classification:1.0.0
    build: .
    environment:
      - PROCESS_NAME=classification
      - PROCESS_VERSION=1.0.0
      - BEHAVIOUR_OF_TEST_PROCESS=create1job
    env_file:
      - ./.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: es.${HOSTNAME}.classification.{{.ID}}
        fluentd-async-connect: "true"
        fluentd-sub-second-precision: "true"


  classification_3:
    image: classification:1.0.0
    build: .
    environment:
      - PROCESS_NAME=classification
      - PROCESS_VERSION=1.0.0
      - BEHAVIOUR_OF_TEST_PROCESS=create1job
    env_file:
      - ./.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: es.server2.classification.{{.ID}}
        fluentd-async-connect: "true"
        fluentd-sub-second-precision: "true"

  classification_4:
    image: classification:1.0.0
    build: .
    environment:
      - PROCESS_NAME=classification
      - PROCESS_VERSION=1.0.0
      - BEHAVIOUR_OF_TEST_PROCESS=create1job
    env_file:
      - ./.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: es.server2.classification.{{.ID}}
        fluentd-async-connect: "true"
        fluentd-sub-second-precision: "true"

  assigner:
    image: assigner:1.0.0
    build: .
    environment:
      - PROCESS_NAME=assigner
      - PROCESS_VERSION=1.0.0
      - BEHAVIOUR_OF_TEST_PROCESS=create4jobs
    env_file:
      - ./.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: es.${HOSTNAME}.assigner.{{.ID}}
        fluentd-async-connect: "true"
        fluentd-sub-second-precision: "true"

  uploader:
    image: uploader:1.0.0
    build: .
    environment:
      - PROCESS_NAME=uploader
      - PROCESS_VERSION=1.0.0
      - BEHAVIOUR_OF_TEST_PROCESS=pipefinish
    env_file:
      - ./.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: es.${HOSTNAME}.uploader.{{.ID}}
        fluentd-async-connect: "true"
        fluentd-sub-second-precision: "true"


  first_process:
    image: first_process:1.9.2
    build: .
    environment:
      - PROCESS_NAME=first_process
      - PROCESS_VERSION=1.9.2
      - BEHAVIOUR_OF_TEST_PROCESS=create1job
    env_file:
      - ./.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: es.${HOSTNAME}.first_process.{{.ID}}
        fluentd-async-connect: "true"
        fluentd-sub-second-precision: "true"


  second_process:
    image: second_process:2.2.0
    build: .
    environment:
      - PROCESS_NAME=second_process
      - PROCESS_VERSION=2.2.0
      - BEHAVIOUR_OF_TEST_PROCESS=create1job
    env_file:
      - ./.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: es.${HOSTNAME}.second_process.{{.ID}}
        fluentd-async-connect: "true"
        fluentd-sub-second-precision: "true"


  third_process:
    image: third_process:5.3.0
    build: .
    environment:
      - PROCESS_NAME=third_process
      - PROCESS_VERSION=5.3.0
      - BEHAVIOUR_OF_TEST_PROCESS=pipefinish
    env_file:
      - ./.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: es.${HOSTNAME}.third_process.{{.ID}}
        fluentd-async-connect: "true"
        fluentd-sub-second-precision: "true"


  summarizing_results:
    image: summarizing_results:1.5.2
    build: .
    environment:
      - PROCESS_NAME=summarizing_results
      - PROCESS_VERSION=1.5.2
      - BEHAVIOUR_OF_TEST_PROCESS=create1job
    env_file:
      - ./.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: es.${HOSTNAME}.summarizing_results.{{.ID}}
        fluentd-async-connect: "true"
        fluentd-sub-second-precision: "true"


  creating_report:
    image: creating_report:1.0.0
    build: .
    environment:
      - PROCESS_NAME=creating_report
      - PROCESS_VERSION=1.0.0
      - BEHAVIOUR_OF_TEST_PROCESS=pipefinish
    env_file:
      - ./.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: es.${HOSTNAME}.creating_report.{{.ID}}
        fluentd-async-connect: "true"
        fluentd-sub-second-precision: "true"
