version: '3.7'
services:
  merging_results_1:
    image: merging_results:1.5.2
    build: .
    depends_on:
      - fluentd
    environment:
      - PROCESS_NAME=merging_results
      - PROCESS_VERSION=1.5.2
    env_file:
      - ./.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: server1.merging_results.{{.ID}}
        fluentd-async-connect: "true"


  merging_results_2:
    image: merging_results:1.5.2
    build: .
    depends_on:
      - fluentd
    environment:
      - PROCESS_NAME=merging_results
      - PROCESS_VERSION=1.5.2
    env_file:
      - ./.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: server1.merging_results.{{.ID}}
        fluentd-async-connect: "true"


  classification_1:
    image: classification:9.1.0
    build: .
    depends_on:
      - fluentd
    environment:
      - PROCESS_NAME=classification
      - PROCESS_VERSION=9.1.0
    env_file:
      - ./.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: server1.classification.{{.ID}}
        fluentd-async-connect: "true"


  classification_2:
    image: classification:1.0.0
    build: .
    links:
      - fluentd
    environment:
      - PROCESS_NAME=classification
      - PROCESS_VERSION=1.0.0
    env_file:
      - ./.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: server1.classification.{{.ID}}
        fluentd-async-connect: "true"


  classification_3:
    image: classification:1.0.0
    build: .
    links:
      - fluentd
    environment:
      - PROCESS_NAME=classification
      - PROCESS_VERSION=1.0.0
    env_file:
      - ./.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: server2.classification.{{.ID}}
        fluentd-async-connect: "true"

  classification_4:
    image: classification:1.0.0
    build: .
    links:
      - fluentd
    environment:
      - PROCESS_NAME=classification
      - PROCESS_VERSION=1.0.0
    env_file:
      - ./.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: server2.classification.{{.ID}}
        fluentd-async-connect: "true"

  assigner:
    image: assigner:1.0.0
    build: .
    links:
      - fluentd
    environment:
      - PROCESS_NAME=assigner
      - PROCESS_VERSION=1.0.0
    env_file:
      - ./.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: server1.assigner.{{.ID}}
        fluentd-async-connect: "true"

  uploader:
    image: uploader:1.0.0
    build: .
    links:
      - fluentd
    environment:
      - PROCESS_NAME=uploader
      - PROCESS_VERSION=1.0.0
    env_file:
      - ./.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: server1.uploader.{{.ID}}
        fluentd-async-connect: "true"


  first_process:
    image: first_process:1.9.2
    build: .
    links:
      - fluentd
    environment:
      - PROCESS_NAME=first_process
      - PROCESS_VERSION=1.9.2
    env_file:
      - ./.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: server1.first_process.{{.ID}}
        fluentd-async-connect: "true"


  second_process:
    image: second_process:2.2.0
    build: .
    links:
      - fluentd
    environment:
      - PROCESS_NAME=second_process
      - PROCESS_VERSION=2.2.0
    env_file:
      - ./.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: server1.second_process.{{.ID}}
        fluentd-async-connect: "true"


  third_process:
    image: third_process:5.3.0
    build: .
    links:
      - fluentd
    environment:
      - PROCESS_NAME=third_process
      - PROCESS_VERSION=5.3.0
    env_file:
      - ./.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: server1.third_process.{{.ID}}
        fluentd-async-connect: "true"


  summarizing_results:
    image: summarizing_results:1.5.2
    build: .
    links:
      - fluentd
    environment:
      - PROCESS_NAME=summarizing_results
      - PROCESS_VERSION=1.5.2
    env_file:
      - ./.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: server1.summarizing_results.{{.ID}}
        fluentd-async-connect: "true"


  creating_report:
    image: creating_report:1.0.0
    build: .
    links:
      - fluentd
    environment:
      - PROCESS_NAME=creating_report
      - PROCESS_VERSION=1.0.0
    env_file:
      - ./.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: server1.creating_report.{{.ID}}
        fluentd-async-connect: "true"


  fluentd:
    image: mcrfluentd:1.0.0
    build: ./fluentd
    depends_on:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"


  elasticsearch:
    environment:
      - "discovery.type=single-node"
    image: elasticsearch:7.3.0
    expose:
      - 9200
    ports:
      - "9200:9200"


  kibana:
    image: kibana:7.3.0
    depends_on:
      - "elasticsearch"
    ports:
      - "5601:5601"
